pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id 'com.android.library' version '8.1.4'
        id 'org.jetbrains.kotlin.android' version '1.9.0'
    }
}

dependencyResolutionManagement {
    repositories {
        // Local Maven repo created by CI to provide the OpenCV AAR as a Maven artifact.
        // AGP does not allow local .aar file dependencies in library projects; this
        // workaround publishes opencv.aar to a minimal Maven repo structure.
        maven { url "$rootDir/libs-repo" }
        google()
        mavenCentral()
    }
}

rootProject.name = 'fingerprint_sdk'
