name: FingerprintSDK
options:
  bundleIdPrefix: com.yellowsense
  deploymentTarget:
    iOS: "13.0"
  xcodeVersion: "15.0"
  podfile: Podfile

targets:
  FingerprintSDK:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - path: Classes
        includes:
          - "**/*.swift"
          - "**/*.h"
          - "**/*.mm"
    settings:
      base:
        SWIFT_VERSION: "5.9"
        DEFINES_MODULE: YES
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES
        SWIFT_OBJC_BRIDGING_HEADER: Classes/Bridging/FingerprintSDK-Bridging-Header.h
        PRODUCT_BUNDLE_IDENTIFIER: com.yellowsense.FingerprintSDK
        CLANG_ENABLE_MODULES: YES
        ENABLE_BITCODE: NO
